# Generated by Django 3.1.2 on 2020-10-13 05:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject_task', to='core.Subject'),
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('label', models.ManyToManyField(blank=True, related_name='subtopic_label', to='core.Label')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='subtopic',
            field=models.ManyToManyField(blank=True, related_name='subtopic_goal', to='core.Subtopic'),
        ),
        migrations.AddField(
            model_name='note',
            name='subtopic',
            field=models.ManyToManyField(blank=True, related_name='subtopic_note', to='core.Subtopic'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtopic',
            field=models.ManyToManyField(blank=True, related_name='subtopic_task', to='core.Subtopic'),
        ),
    ]
