# Generated by Django 3.1.2 on 2020-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuevisionmission',
            old_name='puslish_date',
            new_name='publish_date',
        )
    ]
