# Generated by Django 3.1.2 on 2020-11-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201101_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='task_note', to='core.Task'),
        ),
    ]
