# Generated by Django 3.1.2 on 2020-12-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201101_1221'),
        ('core', '0008_auto_20201026_0253'),
    ]

    operations = [
    ]
