# Generated by Django 3.1.2 on 2020-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201025_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='task_note', to='core.Note'),
        ),
    ]
