# Generated by Django 3.1.2 on 2020-10-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ManyToManyField(blank=True, related_name='goal_task', to='core.Goal'),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pomodoro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
