# Generated by Django 3.1.2 on 2020-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20201212_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definiton',
            field=models.TextField(blank=True, null=True),
        ),
    ]
